name: Build

on:
    pull_request:
      types: [opened, synchronize, reopened]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Cancel Previous Redundant Builds
            uses: styfle/cancel-workflow-action@0.12.1
            with:
              access_token: ${{ secrets.GITHUB_TOKEN }}
          - name: Use checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - name: Use setup-node
            uses: actions/setup-node@v4
            with:
                node-version: '20.x'
          - name: Install dependencies
            run: npm ci
          - name: Build
            run: npm run build
